version: '2'
services:
  grappler:
    command: yarn dev
    build:
      context: ./grappler
    volumes:
      - ./grappler:/grappler
    ports:
      - '3000:3000'
  deflector-nodejs:
    command: yarn dev
    build:
      context: ./deflector-nodejs
    volumes:
      - ./deflector-nodejs:/deflector
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "kafka-test-topic:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: 10.0.0.6 # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis
    ports:
        - "6379"
  rabbitmq:
    image: rabbitmq:3.7.3-management-alpine
    ports:
      - "4369"
      - "5671"
      - "5672"
      - "25672"
      - "15672:15672"
